
-- 牌面
cc.exports.DDZ_3D   = 0
cc.exports.DDZ_3C   = 1
cc.exports.DDZ_3H   = 2
cc.exports.DDZ_3S   = 3
cc.exports.DDZ_4D   = 4
cc.exports.DDZ_4C   = 5
cc.exports.DDZ_4H   = 6
cc.exports.DDZ_4S   = 7
cc.exports.DDZ_5D   = 8
cc.exports.DDZ_5C   = 9
cc.exports.DDZ_5H   = 10
cc.exports.DDZ_5S   = 11
cc.exports.DDZ_6D   = 12
cc.exports.DDZ_6C   = 13
cc.exports.DDZ_6H   = 14
cc.exports.DDZ_6S   = 15
cc.exports.DDZ_7D   = 16
cc.exports.DDZ_7C   = 17
cc.exports.DDZ_7H   = 18
cc.exports.DDZ_7S   = 19
cc.exports.DDZ_8D   = 20
cc.exports.DDZ_8C   = 21
cc.exports.DDZ_8H   = 22
cc.exports.DDZ_8S   = 23
cc.exports.DDZ_9D   = 24
cc.exports.DDZ_9C   = 25
cc.exports.DDZ_9H   = 26
cc.exports.DDZ_9S   = 27
cc.exports.DDZ_10D  = 28
cc.exports.DDZ_10C  = 29
cc.exports.DDZ_10H  = 30
cc.exports.DDZ_10S  = 31
cc.exports.DDZ_JD   = 32
cc.exports.DDZ_JC   = 33
cc.exports.DDZ_JH   = 34
cc.exports.DDZ_JS   = 35
cc.exports.DDZ_QD   = 36
cc.exports.DDZ_QC   = 37
cc.exports.DDZ_QH   = 38
cc.exports.DDZ_QS   = 39
cc.exports.DDZ_KD   = 40
cc.exports.DDZ_KC   = 41
cc.exports.DDZ_KH   = 42
cc.exports.DDZ_KS   = 43
cc.exports.DDZ_AD   = 44
cc.exports.DDZ_AC   = 45
cc.exports.DDZ_AH   = 46
cc.exports.DDZ_AS   = 47
cc.exports.DDZ_2D   = 48
cc.exports.DDZ_2C   = 49
cc.exports.DDZ_2H   = 50
cc.exports.DDZ_2S   = 51
cc.exports.DDZ_BJ   = 52 -- 小王 black joker
cc.exports.DDZ_CJ   = 53 -- 大王 color joker

cc.exports.DDZ_IMAGE = {
    [DDZ_3D]    = "Poker_103.png",
    [DDZ_3C]    = "Poker_203.png",
    [DDZ_3H]    = "Poker_303.png",
    [DDZ_3S]    = "Poker_403.png",
    [DDZ_4D]    = "Poker_104.png",
    [DDZ_4C]    = "Poker_204.png",
    [DDZ_4H]    = "Poker_304.png",
    [DDZ_4S]    = "Poker_404.png",
    [DDZ_5D]    = "Poker_105.png",
    [DDZ_5C]    = "Poker_205.png",
    [DDZ_5H]    = "Poker_305.png",
    [DDZ_5S]    = "Poker_405.png",
    [DDZ_6D]    = "Poker_106.png",
    [DDZ_6C]    = "Poker_206.png",
    [DDZ_6H]    = "Poker_306.png",
    [DDZ_6S]    = "Poker_406.png",
    [DDZ_7D]    = "Poker_107.png",
    [DDZ_7C]    = "Poker_207.png",
    [DDZ_7H]    = "Poker_307.png",
    [DDZ_7S]    = "Poker_407.png",
    [DDZ_8D]    = "Poker_108.png",
    [DDZ_8C]    = "Poker_208.png",
    [DDZ_8H]    = "Poker_308.png",
    [DDZ_8S]    = "Poker_408.png",
    [DDZ_9D]    = "Poker_109.png",
    [DDZ_9C]    = "Poker_209.png",
    [DDZ_9H]    = "Poker_309.png",
    [DDZ_9S]    = "Poker_409.png",
    [DDZ_10D]   = "Poker_110.png",
    [DDZ_10C]   = "Poker_210.png",
    [DDZ_10H]   = "Poker_310.png",
    [DDZ_10S]   = "Poker_410.png",
    [DDZ_JD]    = "Poker_111.png",
    [DDZ_JC]    = "Poker_211.png",
    [DDZ_JH]    = "Poker_311.png",
    [DDZ_JS]    = "Poker_411.png",
    [DDZ_QD]    = "Poker_112.png",
    [DDZ_QC]    = "Poker_212.png",
    [DDZ_QH]    = "Poker_312.png",
    [DDZ_QS]    = "Poker_412.png",
    [DDZ_KD]    = "Poker_113.png",
    [DDZ_KC]    = "Poker_213.png",
    [DDZ_KH]    = "Poker_313.png",
    [DDZ_KS]    = "Poker_413.png",
    [DDZ_AD]    = "Poker_101.png",
    [DDZ_AC]    = "Poker_201.png",
    [DDZ_AH]    = "Poker_301.png",
    [DDZ_AS]    = "Poker_401.png",
    [DDZ_2D]    = "Poker_102.png",
    [DDZ_2C]    = "Poker_202.png",
    [DDZ_2H]    = "Poker_302.png",
    [DDZ_2S]    = "Poker_402.png",
    [DDZ_BJ]    = "Poker_514.png",
    [DDZ_CJ]    = "Poker_515.png"
}

cc.exports.DDZ = {
    -- 点数
    Point = {
        P0  = 0,
        P3  = 3,
        P4  = 4,
        P5  = 5,
        P6  = 6,
        P7  = 7,
        P8  = 8,
        P9  = 9,
        P10 = 10,
        PJ  = 11,
        PQ  = 12,
        PK  = 13,
        PA  = 14,
        P2  = 15,
        PB  = 16,
        PC  = 17
    },
    -- 牌型
    Comb = {
        None       = 0,
	    Single     = 1,  -- 单张
	    Pair       = 2,  -- 对子
	    Triplet    = 3,  -- 三张
	    Triplet1   = 4,  -- 三带一
	    Triplet2   = 5,  -- 三带对
	    Sequence   = 6,  -- 顺子（至少5张）
	    Pairs      = 7,  -- 连对（至少3对）
	    Triplets   = 8,  -- 飞机
	    Triplets1  = 9,  -- 飞机带单
	    Triplets2  = 10, -- 飞机带对
  	    Quadplex2  = 11, -- 四带二
	    Quadplex4  = 12, -- 四带二对
	    Bomb       = 13, -- 炸弹
	    Rocket     = 14, -- 火箭
    },
    -- 操作类型
    Action = {
        Call  = "call",  -- 叫地主
        Raise = "raise", -- 加倍（农民）
        Play  = "play"   -- 出牌
    },
    -- 消息类型
    Msg = {
        -- server -> client
        GameInfo  = "gameInfo",  -- 游戏信息
        Deal      = "deal",      -- 发牌
        CallTime  = "calling",   -- 发牌阶段
        Call      = "call",      -- 玩家叫地主
        Landlord  = "landlord",  -- 确定地主
        RaiseTime = "raising",   -- 农民加倍阶段
        Raise     = "raise",     -- 农民加倍
        PlayTime  = "playing",   -- 出牌阶段
        Play      = "play",      -- 玩家出牌
        GameEnd   = "gameEnd",   -- 游戏结束
        WhoseTurn = "who",       -- 轮到谁做什么
        AutoOn    = "auto",      -- 托管
        AutoOff   = "manual",    -- 取消托管
        NoLandlord= "nolandlord", -- 叫地主超时解散
        -- client -> server
        PlayerCall    = "call",
        PlayerRaise   = "raise",
        PlayerPlay    = "play",
        PlayerAutoOn  = "auto",
        PlayerAutoOff = "manual"
    }
}